[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = ["day1", "day10", "day1_faster", "day2", "day3", "day3_faster", "day3_small", "day4", "day5", "day6", "day7", "day8", "day9"]
